### ISSUE TITLE
Error when running main.py twice

### ISSUE THREAD

**Issue by zacharycope0** [QUIC-Fire-TT/ttrs_quicfire#9]
**Describe the bug**
When I run the main.py script (in EXAMPLE_SETUP) more than once in the Spyder terminal I get an error on the second run. For some reason we must be overwriting print_inp_files and not reimporting it on the second run.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671145/171735755-02246b7b-7357-407d-97c6-8229a30f5ed1.png)

**Comment by cbonesteel** [comment]
This is a rather odd error to me because we shouldn't be overwritting ```print_inp_files.py``` at all since it is a python file within our package installation. I would check that the file is still in your ```site-packages``` directory after the first run, there is no reason it shouldn't be. If it is there and the problem persists, then there might be an issue with the way its setup with the Syder terminal. I don't think its an issue with the actual code because I am able to run it using my python installation through a command line interface just fine. I'll try and do some more digging, but I find this to be very weird. Once we figure this out we will need to document this for our FAQ section down the road because I'm sure it will come up again.
